In [ ]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def __call__(self, value):
        return math.pi * self.radius**2 * (value or 1)  # 如果value为None，则默认计算面积，否则乘以value
    @property
    def points(self):
        return self(None)

# 创建一个半径为5的圆
my_circle = Circle(5)

# 调用__call__方法，传入None作为参数，相当于计算面积
print(my_circle.points)  # 输出: 78.53981633974483

# 调用__call__方法，传入3作为参数，相当于计算圆面积并乘以3
print(my_circle(3))  # 输出: 235.61944901923448




In [ ]:
class MyModel(nn.Module):
    def forward(self, x):
        return x

model = MyModel()
output = model.forward(input_data, additional_param)


In [6]:
import numpy as np

# 假设 inputs 是一个张量或数组
inputs = np.array([2, 3, 4])  # 示例值，可以根据需要修改

# 设置随机数生成器
rng = np.random.default_rng(seed=12345)  # 你可以根据需要设置种子

# 使用 randint 生成随机整数
random_integers = rng.integers(low=0, high=2, size=inputs.tolist(), dtype=np.int32)

# 转换数据类型
result = random_integers.astype(np.float32)  # self._dtype 在此示例中假设为 float32

print(result)


[[[1. 0. 1. 0.]
  [0. 1. 1. 1.]
  [1. 0. 1. 0.]]

 [[1. 1. 0. 0.]
  [0. 1. 1. 1.]
  [1. 0. 1. 1.]]]


In [1]:
import torch

# 检查是否有可用的 GPU
if torch.cuda.is_available():
    # 获取当前设备
    device = torch.device('cuda')
    
    # 打印当前设备的总内存和已使用内存
    print(f"Total memory: {torch.cuda.get_device_properties(device).total_memory / 1024**3:.2f} GB")
    print(f"Allocated memory: {torch.cuda.memory_allocated(device) / 1024**3:.2f} GB")
    print(f"Cached memory: {torch.cuda.memory_reserved(device) / 1024**3:.2f} GB")
else:
    print("CUDA is not available.")


Total memory: 8.00 GB
Allocated memory: 0.00 GB
Cached memory: 0.00 GB
